---
title: "Posit Documentation Theme Example"
format:
  posit-docs-html: default
---

## Level Two

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? [33] At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.

### Level Three

1. Steps
2. Steps steps
3. Steps steps **Steps**.


- Lists
- Lists lists
- Another list
    - And another list


### Another Level Three {.preview-header} 

```bash
$ sudo rstudio-server restart
$ sudo rstudio-launcher restart
```

```{.ini filename="/etc/rstudio/rserver.conf"}
launcher-sessions-container-images=rstudio/r-session-complete:jammy-<workbench version>
launcher-adhoc-container-images=rstudio/r-session-complete:jammy-<workbench version>
```

``` txt
Checking Job Launcher configuration...
Ensuring server-user is a Job Launcher admin...
Getting list of Job Launcher clusters...
Job launcher configured with the following clusters: Kubernetes, Local
launcher-adhoc-clusters is empty - all clusters may be used to launch adhoc jobs
launcher-sessions-clusters is empty - all clusters may be used to launch session jobs
02 May 2020 05:29:35 [rserver] WARNING Project sharing is currently not supported when running launcher sessions. 
It has automatically been disabled for session 4d4356ec67e7babe88f4a; LOGGED FROM: 
void rstudio::server::job_launcher::setProfile(const string&, const string&, const string&, const string&, 
bool, rstudio::core::r_util::SessionLaunchProfile*)
/var/lib/jenkins/workspace/IDE/pro-pipeline/v1.2-patch/src/cpp/server/ServerJobLauncher.cpp:107
Launched R session job for cluster Kubernetes and image rstudio/r-session-complete:jammy-<workbench version>
Waiting for job to run...
Job transitioned to status Pending
Job transitioned to status Pending with status message: Created pod: session-4d4356ec67e7babe88f4a-rstudio---session-test-job-xkbfw2
Job transitioned to status Pending with status message: 
Successfully assigned rstudio/session-4d4356ec67e7babe88f4a-rstudio---session-test-job-xkbfw2 to ip-172-31-30-139.us-east-2.compute.internal
Job transitioned to status Pending with status message: containers with unready status: [50506d5573575359475966796a636c2b3342333574413d3d]
Job transitioned to status Pending with status message: Container image "rstudio/r-session-complete:jammy-<workbench version>" already present on machine
Job transitioned to status Pending with status message: Created container 50506d5573575359475966796a636c2b3342333574413d3d
Job transitioned to status Pending with status message: Started container 50506d5573575359475966796a636c2b3342333574413d3d
Job is running
Waiting for job to finish...
Job has finished running
Job exited successfully
02 May 2020 05:29:40 [rserver] WARNING Project sharing is currently not supported when running launcher sessions. 
It has automatically been disabled for session 4d4356ec67e7b2e24a23f; 
LOGGED FROM: void rstudio::server::job_launcher::setProfile(const string&, const string&, const string&, const string&, 
bool, rstudio::core::r_util::SessionLaunchProfile*) /var/lib/jenkins/workspace/IDE/pro-pipeline/v1.2-patch/src/cpp/server/ServerJobLauncher.cpp:1070
Launched R session job for cluster Local
Waiting for job to run...
Job transitioned to status Pending
Job is running
Waiting for job to finish...
Job has finished running
Job exited successfully
```


## Level Two Again

::: panel-tabset

### RHEL

```bash
$ yum install rstudio-workbench-rhel
```

### Ubuntu | Debian

```bash
$ dpkg
```

### SUSE

```bash
$ zypper
```

:::

### Level three

:::{.callout-note}
Something
:::

:::{.callout-tip}
Something
:::

:::{.callout-caution}
Something
:::

:::{.callout-warning}
Something
:::

:::{.callout-important}
Something
:::

